# Site settings
title: portfolio website
description: A blog about me 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: V.A.S.Abhinav
user_description: currently under developement , will upload project links after the page is finished
user_title: Student, Football fanatic , ML enthusiast
email: veldandaabhinav@gmail.com
github_username:  chel310


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
